import React, { useState } from 'react';
import { Download, History, Loader2, CheckCircle2 } from 'lucide-react';
import { useToast } from './ToastNotifications';
import { recentReportsData } from '../../data/reportsData';

const ReportHistory = () => {
  const { addToast } = useToast();
  const [downloadingId, setDownloadingId] = useState(null);

  const handleDownload = (id, name) => {
    setDownloadingId(id);
    setTimeout(() => {
      setDownloadingId(null);
      addToast(`${name} downloaded successfully.`, 'success');
    }, 1500);
  };

  return (
    <div className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden mt-6">
      <div className="p-5 border-b border-slate-100 flex items-center gap-2 bg-slate-50/50">
        <History size={18} className="text-slate-500" />
        <h3 className="text-base font-semibold text-slate-800">Report History Archive</h3>
      </div>
      
      <div className="overflow-x-auto">
        <table className="w-full text-left border-collapse min-w-[800px]">
          <thead>
            <tr className="bg-slate-50 text-slate-500 text-xs uppercase tracking-wider border-b border-slate-100">
              <th className="px-6 py-4 font-semibold">Report</th>
              <th className="px-6 py-4 font-semibold">Generated By</th>
              <th className="px-6 py-4 font-semibold">Generated On</th>
              <th className="px-6 py-4 font-semibold">Department</th>
              <th className="px-6 py-4 font-semibold text-center">Status</th>
              <th className="px-6 py-4 font-semibold text-right">Download</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-100 text-sm">
            {recentReportsData.map((report) => (
              <tr key={`hist-${report.id}`} className="hover:bg-slate-50/50 transition-colors">
                <td className="px-6 py-4 font-medium text-slate-800">{report.name}</td>
                <td className="px-6 py-4 text-slate-600">{report.generatedBy}</td>
                <td className="px-6 py-4 text-slate-500">{new Date(report.date).toLocaleDateString()}</td>
                <td className="px-6 py-4 text-slate-600">{report.department}</td>
                <td className="px-6 py-4 text-center">
                  <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-xs font-medium bg-emerald-100 text-emerald-700">
                    <CheckCircle2 size={12}/> {report.status}
                  </span>
                </td>
                <td className="px-6 py-4 text-right">
                  <button 
                    onClick={() => handleDownload(report.id, report.name)}
                    disabled={downloadingId === report.id}
                    className="inline-flex items-center justify-center w-8 h-8 rounded text-slate-400 hover:text-blue-600 hover:bg-blue-50 transition-colors disabled:opacity-50"
                  >
                    {downloadingId === report.id ? <Loader2 size={16} className="animate-spin" /> : <Download size={16} />}
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
};

export default ReportHistory;
