# Generated by Django 5.1.15 on 2026-07-12 04:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentEnvironmentalScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('total_emissions', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('goals_achieved', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='environmental_score', to='users.department')),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('factor', models.DecimalField(decimal_places=6, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('unit', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category', 'status'], name='environment_categor_8adb46_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductESGProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(db_index=True, max_length=255)),
                ('sku', models.CharField(db_index=True, max_length=100, unique=True)),
                ('carbon_footprint', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('water_footprint', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('recyclability_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20)),
            ],
            options={
                'ordering': ['product_name'],
                'indexes': [models.Index(fields=['sku', 'status'], name='environment_sku_fedb2b_idx')],
            },
        ),
        migrations.CreateModel(
            name='CarbonTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(db_index=True, max_length=100)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('unit', models.CharField(max_length=50)),
                ('calculated_co2', models.DecimalField(blank=True, db_index=True, decimal_places=4, max_digits=14)),
                ('transaction_date', models.DateField(db_index=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carbon_transactions', to='users.department')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carbon_transactions', to='users.employeeprofile')),
                ('emission_factor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='environmental.emissionfactor')),
            ],
            options={
                'ordering': ['-transaction_date'],
                'indexes': [models.Index(fields=['department', 'transaction_date'], name='environment_departm_9a5e13_idx'), models.Index(fields=['activity_type', 'transaction_date'], name='environment_activit_8a3458_idx')],
            },
        ),
        migrations.CreateModel(
            name='EnvironmentalGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('target_type', models.CharField(choices=[('carbon_reduction', 'Carbon Reduction'), ('water_saving', 'Water Saving'), ('waste_reduction', 'Waste Reduction')], db_index=True, max_length=50)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('current_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('start_date', models.DateField()),
                ('target_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('achieved', 'Achieved'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=20)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='users.department')),
            ],
            options={
                'ordering': ['target_date'],
                'indexes': [models.Index(fields=['target_type', 'status'], name='environment_target__d6d101_idx'), models.Index(fields=['department', 'status'], name='environment_departm_d8e8dd_idx')],
            },
        ),
    ]
