# Generated by Django 5.1.15 on 2026-07-12 05:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSRActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('points', models.PositiveIntegerField(default=10)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed')], db_index=True, default='upcoming', max_length=20)),
                ('category', models.ForeignKey(limit_choices_to={'type': 'csr_activities'}, on_delete=django.db.models.deletion.CASCADE, related_name='csr_activities', to='users.category')),
            ],
            options={
                'verbose_name': 'CSR Activity',
                'verbose_name_plural': 'CSR Activities',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentSocialScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('total_csr_points', models.PositiveIntegerField(default=0)),
                ('training_hours_per_employee', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_score', to='users.department')),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('trainer', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration_hours', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], db_index=True, default='scheduled', max_length=20)),
                ('employees', models.ManyToManyField(blank=True, related_name='trainings', to='users.employeeprofile')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='DiversityMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_date', models.DateField(db_index=True)),
                ('gender_distribution', models.JSONField(default=dict)),
                ('age_distribution', models.JSONField(default=dict)),
                ('disability_count', models.PositiveIntegerField(default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diversity_metrics', to='users.department')),
            ],
            options={
                'verbose_name': 'Diversity Metric',
                'verbose_name_plural': 'Diversity Metrics',
                'ordering': ['-metric_date'],
                'indexes': [models.Index(fields=['department', 'metric_date'], name='social_dive_departm_4408d8_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence', models.FileField(blank=True, null=True, upload_to='evidence/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('points_awarded', models.PositiveIntegerField(default=0)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='social.csractivity')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='users.employeeprofile')),
            ],
            options={
                'verbose_name': 'Employee Participation',
                'verbose_name_plural': 'Employee Participations',
                'ordering': ['-joined_date'],
                'unique_together': {('employee', 'activity')},
            },
        ),
    ]
