# Generated by Django 5.1.15 on 2026-07-12 04:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment_weight', models.DecimalField(decimal_places=2, default=33.33, max_digits=5)),
                ('social_weight', models.DecimalField(decimal_places=2, default=33.33, max_digits=5)),
                ('governance_weight', models.DecimalField(decimal_places=2, default=33.34, max_digits=5)),
                ('auto_emission_calculation', models.BooleanField(default=False)),
                ('require_evidence', models.BooleanField(default=True)),
                ('auto_badge_unlock', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Organization Settings',
                'verbose_name_plural': 'Organization Settings',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('type', models.CharField(choices=[('csr_activities', 'CSR Activities'), ('challenges', 'Challenges')], db_index=True, max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['type', 'status'], name='users_categ_type_3ea734_idx')],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Code must contain only uppercase alphanumeric characters, underscores, or hyphens.', regex='^[A-Z0-9_-]+$')])),
                ('employee_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20)),
                ('parent_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_departments', to='users.department')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(db_index=True, max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Employee ID must contain only alphanumeric characters, underscores, or hyphens.', regex='^[a-zA-Z0-9_-]+$')])),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='users.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['employee_id'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='users.employeeprofile'),
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('badge_notifications', models.BooleanField(default=True)),
                ('csr_notifications', models.BooleanField(default=True)),
                ('challenge_notifications', models.BooleanField(default=True)),
                ('policy_notifications', models.BooleanField(default=True)),
                ('compliance_notifications', models.BooleanField(default=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='users.employeeprofile')),
            ],
            options={
                'verbose_name': 'Notification Settings',
                'verbose_name_plural': 'Notification Settings',
            },
        ),
        migrations.AddIndex(
            model_name='employeeprofile',
            index=models.Index(fields=['employee_id', 'status'], name='users_emplo_employe_cbb929_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeprofile',
            index=models.Index(fields=['department', 'status'], name='users_emplo_departm_678069_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['code', 'status'], name='users_depar_code_7d7398_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['parent_department', 'status'], name='users_depar_parent__c4d791_idx'),
        ),
    ]
